version: '3.9'

services:
  
  app-provisioner:
    env_file:
      - env.dev
    image: pennsieve/app-provisioner
    volumes:
      - ./terraform:/usr/src/app/terraform
      - $HOME/.aws:/root/.aws:ro
    container_name: app-provisioner
    build:
      context: .
      dockerfile: ./Dockerfile